import { test, devices, expect } from '@playwright/test';

test.use({
    browserName: 'chromium',
    ...devices['iPhone XR'],
    viewport: { width: 414, height: 896 }
})

test.describe('Head tag area', () => {
    test("Contains the head tag and its contents", async ({ page }) => {
        await page.goto('http://localhost:3000/');
        await expect(page).toHaveTitle('Spotify App');
        const metaDescription = page.locator('meta[name="description"]');
        await expect(metaDescription).toHaveAttribute('content', 'Generated by Marian Francisco');
        const linkIcon = page.locator('link[rel="icon"]');
        await expect(linkIcon).toHaveAttribute('href','/spotifyfavicon.png');
    })
})

test.describe('Button test', () => {
    test('This is the info component', async ({ page }) => {
        await page.goto('http://localhost:3000');
        await expect(page.locator('button')).toContainText("Get Started")
    })
})
