import { test, expect } from '@playwright/test'

test.describe('Head tag area', () => {
    test("Contains the head tag and its contents", async ({ page }) => {
        await page.goto('http://localhost:3000/');
        await expect(page).toHaveTitle('Spotify App');
        const metaDescription = page.locator('meta[name="description"]');
        await expect(metaDescription).toHaveAttribute('content', 'Generated by Marian Francisco');
        const linkIcon = page.locator('link[rel="icon"]');
        await expect(linkIcon).toHaveAttribute('href','/spotifyfavicon.png');
    })
})
